//! `acmex init` — project scaffolding command.
//!
//! Creates a self-contained AcmeX working directory: a validated
//! `acmex.toml` configuration, the storage/repository/secret directories the
//! config references, and a short "next steps" guide. The command is
//! idempotent-safe: an existing `acmex.toml` is never overwritten.
//!
//! ```text
//! acmex init                          # scaffold ./acmex.toml + .acmex/
//! acmex init --dir /srv/acmex         # scaffold into another directory
//! acmex init --ca letsencrypt --env production --challenge dns-01
//! ```

use std::path::PathBuf;

use std::str::FromStr;

use crate::config::Config;
use crate::error::{AcmeError, Result};

/// Options accepted by `acmex init` (see `cli::args::InitArgs`).
#[derive(Debug, Clone)]
pub struct InitOptions {
    /// Root directory to scaffold into (`.` by default).
    pub dir: PathBuf,
    /// CA id written into `[acme].ca` (`letsencrypt`, `google`, ...).
    pub ca: String,
    /// CA environment: `staging` (default) or `production`.
    pub env: String,
    /// Default challenge type (`dns-01`, `http-01`, `tls-alpn-01`).
    pub challenge: String,
    /// Contact email for the ACME account.
    pub email: Option<String>,
}

impl InitOptions {
    /// The config file path inside the target directory.
    fn config_path(&self) -> PathBuf {
        self.dir.join("acmex.toml")
    }

    /// Storage directories referenced by the generated config.
    fn data_dirs(&self) -> Vec<PathBuf> {
        vec![
            self.dir.join(".acmex/certs"),
            self.dir.join(".acmex/repository"),
            self.dir.join(".acmex/secrets"),
        ]
    }
}

/// Renders the scaffold configuration from the options.
///
/// The template intentionally contains **no secrets**: credentials are
/// supplied at runtime through `SecretRef` (`env:`/`file:`) per the v0.9
/// security baseline, and the management API keys come from
/// `ACMEX_API_KEYS`.
fn render_config(options: &InitOptions) -> String {
    let contact = options
        .email
        .as_deref()
        .map(|email| format!("mailto:{email}"))
        .unwrap_or_else(|| "mailto:admin@example.com".to_string());
    format!(
        r#"# AcmeX configuration — generated by `acmex init`.
#
# Secrets never live in this file:
#   * Management API keys:    export ACMEX_API_KEYS="key1,key2"
#   * DNS provider tokens:    [[challenge.dns01.providers]] api_token = "env:CF_DNS_TOKEN"
#   * Webhook signing:        [notifications.webhook] signing_secret = "file:/run/secrets/wh"
#
# Validate any edit before deploying:   acmex serve --config acmex.toml --addr 127.0.0.1:18080

[acme]
ca = "{ca}"
ca_environment = "{env}"
contact = ["{contact}"]
tos_agreed = true

# File storage for legacy bundles and the durable repository (intents,
# lineages, versions, operations, outbox). All state survives restarts.
[storage]
backend = "file"

[storage.file]
path = ".acmex/certs"

[repository]
backend = "file"
namespace = "default"

[repository.file]
path = ".acmex/repository"

# Legacy `cert:*` bundles are imported by switching this to "dry-run" or
# "execute" once (see docs/roadmap/v0.9.0/T02_REPOSITORY_AND_MIGRATION.md).
[repository.migration]
mode = "off"

[challenge]
challenge_type = "{challenge}"

# HTTP-01: an embedded listener serving /.well-known/acme-challenge/<token>.
# Keep on loopback behind an ingress that forwards port 80, or point an edge
# agent at it.
[challenge.http01]
listen_addr = "127.0.0.1:5002"
challenge_path = ".well-known/acme-challenge"

# DNS-01: one block per provider instance. `api_token` is a SecretRef —
# `env:VAR` or `file:/path`. Credentials are resolved at startup only.
# [[challenge.dns01.providers]]
# name = "cloudflare"
# api_token = "env:CF_DNS_TOKEN"
# zone_id = "..."
# [challenge.dns01.providers.extra]
# zone_id = "..."
[challenge.dns01]
propagation_timeout_secs = 300

[tls_alpn]
listen_addr = "127.0.0.1:5001"

# Renewal scanning: the controller prefers ARI (RFC 9773) when the CA
# offers it and falls back to a 2/3-lifetime window otherwise.
[renewal]
check_interval = 3600
renew_before_days = 30
max_retries = 3
retry_delay_secs = 300
concurrency = 5

# Prometheus scrape endpoint (unauthenticated, keep on loopback).
[metrics]
enabled = true
listen_addr = "127.0.0.1:9090"

[server]
listen_addr = "127.0.0.1:8080"
enable_api = true
enable_webhook = true
"#,
        ca = options.ca,
        env = options.env,
        contact = contact,
        challenge = options.challenge,
    )
}

/// Validates that the CA/challenge/environment combination is coherent
/// before anything is written.
fn validate_options(options: &InitOptions) -> Result<()> {
    let known_cas = ["letsencrypt", "google", "zerossl", "custom"];
    if !known_cas.contains(&options.ca.as_str()) {
        return Err(AcmeError::invalid_input(format!(
            "unknown CA `{}` (expected one of {known_cas:?})",
            options.ca
        )));
    }
    if !["staging", "production"].contains(&options.env.as_str()) {
        return Err(AcmeError::invalid_input(format!(
            "unknown environment `{}` (expected `staging` or `production`)",
            options.env
        )));
    }
    if !["dns-01", "http-01", "tls-alpn-01"].contains(&options.challenge.as_str()) {
        return Err(AcmeError::invalid_input(format!(
            "unknown challenge type `{}` (expected dns-01, http-01 or tls-alpn-01)",
            options.challenge
        )));
    }
    Ok(())
}

/// Runs `acmex init`.
///
/// Steps: validate options → refuse overwrite → write `acmex.toml` →
/// create data directories → parse the file back with [`Config`] to prove
/// the scaffold is valid → print next steps.
pub async fn handle_init(options: InitOptions) -> Result<()> {
    validate_options(&options)?;

    let config_path = options.config_path();
    if config_path.exists() {
        return Err(AcmeError::Conflict(format!(
            "`{}` already exists; `acmex init` never overwrites an existing configuration",
            config_path.display()
        )));
    }

    println!("🏗️  Scaffolding AcmeX project in {}", options.dir.display());
    println!("   CA: {} ({})", options.ca, options.env);
    println!("   Challenge: {}", options.challenge);

    // 1. Configuration file.
    let rendered = render_config(&options);
    if let Some(parent) = config_path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&config_path, &rendered)?;

    // 2. Data directories referenced by the config.
    for dir in options.data_dirs() {
        std::fs::create_dir_all(&dir)?;
        println!("   ✓ dir  {}", dir.display());
    }
    println!("   ✓ file {}", config_path.display());

    // 3. Round-trip validation: the scaffold must parse and validate.
    let parsed = Config::from_str(&rendered)?;
    let ca_config = parsed.acme.to_ca_config()?;
    let directory = ca_config
        .directory_url()
        .map_err(AcmeError::configuration)?;
    println!("   ✓ config validates (directory: {directory})");

    // 4. Next steps.
    println!(
        "\nNext steps:\n  \
         1. Set management API keys:      export ACMEX_API_KEYS=\"dev-key\"\n  \
         2. Add a DNS provider token:     edit [challenge.dns01.providers] in {}\n  \
         3. Start the server + worker:    acmex serve --config {} --addr 127.0.0.1:8080\n  \
         4. Request a certificate:        curl -X POST localhost:8080/api/v1/certificate-intents ...",
        config_path.display(),
        config_path.display()
    );
    if options.env != "production" {
        println!(
            "\nℹ️  Staging environment: certificates are NOT trusted; switch `ca_environment = \"production\"` when ready."
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "acmex-init-{tag}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        dir
    }

    #[test]
    fn rejects_unknown_options_before_touching_disk() {
        let options = InitOptions {
            dir: PathBuf::from("/definitely/not/created"),
            ca: "not-a-ca".to_string(),
            env: "staging".to_string(),
            challenge: "dns-01".to_string(),
            email: None,
        };
        assert!(validate_options(&options).is_err());
        assert!(!std::path::Path::new("/definitely/not/created/acmex.toml").exists());
    }

    #[tokio::test]
    async fn scaffolds_valid_project_and_refuses_overwrite() {
        let dir = temp_dir("ok");
        let options = InitOptions {
            dir: dir.clone(),
            ca: "letsencrypt".to_string(),
            env: "staging".to_string(),
            challenge: "dns-01".to_string(),
            email: Some("ops@example.com".to_string()),
        };

        handle_init(options.clone()).await.unwrap();

        // Config written, parses, and carries the chosen options.
        let raw = std::fs::read_to_string(dir.join("acmex.toml")).unwrap();
        let config = Config::from_str(&raw).unwrap();
        assert_eq!(config.acme.ca, "letsencrypt");
        assert_eq!(config.challenge.challenge_type, "dns-01");
        assert!(raw.contains("mailto:ops@example.com"));
        assert!(!raw.contains("PRIVATE KEY"));
        // No literal secrets: the only credential mention is the commented
        // SecretRef example (`env:` reference, never a plaintext value).
        for line in raw.lines().filter(|l| l.contains("api_token =")) {
            assert!(
                line.trim_start().starts_with('#'),
                "uncommented secret: {line}"
            );
            assert!(
                line.contains("env:"),
                "secret example must be a SecretRef: {line}"
            );
        }

        // Data directories exist.
        assert!(dir.join(".acmex/certs").is_dir());
        assert!(dir.join(".acmex/repository").is_dir());
        assert!(dir.join(".acmex/secrets").is_dir());

        // Second init refuses to overwrite.
        let again = handle_init(options).await;
        assert!(again.is_err());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
